# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
