# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('source_code_link', models.CharField(max_length=50)),
                ('long_descriptino', models.CharField(max_length=1000)),
            ],
        ),
    ]
