# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='long_descriptino',
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
