# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_screenshot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='store_logo_url',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='store_url',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
