# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20160801_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(default=1.0, max_length=30),
            preserve_default=False,
        ),
    ]
