# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20160802_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies_used',
            field=models.CharField(max_length=300),
        ),
    ]
